nelmio_api_doc:
  documentation:
    info:
      title: 'Todo List API'
      description: 'This is a REST API for managing users and tasks. It allows users to perform various operations on tasks, such as creating, editing, marking as completed, and deleting tasks.'
      version: '1.0.0'
  areas:
    path_patterns:
      - ^/v1/api
